---
sudo: required
dist: trusty
language: node_js
node_js:
  - 14.0.0

branches:
  only:
    - 07-deployment

cache:
  directories:
    - node_modules

services:
  - docker

env:
  global:
    - NODE_ENV=local # should be TEST!

install:
  - npm install

before_script:
  - sudo service postgresql stop
  - docker ps
  - npm run infra
  - sleep 5
  - npm run db:migrate:deploy # should be without :deploy (but test env does not work yet)

script:
  - npm run test:coverage

after_success:
  - echo Upload code coverage # homework
  - npm run test:upload

notifications:
  - email: false

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      - secure: 'qk+hXh9Z/0ncRWcMoA/BuDYeOPoB53MfR+rjyPudbU/S13O+OhuPKhdOEsEq18U8gYnFH9FV0OpmCXa6LiTxvhtjIMV7Q4SW4Hu0Eq+7OLbY6NVeprdK1AVYu8vyKBqKegx79EzQmCh8+JxLWwMcmNmDf6bO38kcjwNSb6MpzGgZsmlS3McGGKxsF9I8pzBx15cD6BEPGqNBXMKY7nUHXIi2uw6k36ZEdlGl1oHV/MCMfJLBv0ny6+/QENZb+uUFhBcVnVvghIwzDVQzNsQVB6duKHcdCVw+3x5PAuP/RFFkOzRxHmPRcSKQChDyhxvjkbB9idTYjZSFs2HkEInAryHgwS0o0abGoXCkwgwgmGvTE/pMPCgPYawZJebnjGT0yxZePv+Do5+fn7F9Wj6phpKiOSq55ZmcJlIyJ/gz2OpglhEtGaIsnKg80txfltfhCgnQdtEbNcxd4Ck6cF5ErCsW0lNCdcgpSYiJoaUzDs4CJ/VEUKovnYEIGI0y0LRZHYxkhHq+vC7GFIq2lcASI7phd7a0SmSWzwd9gAqUQSVNSXEYC0AyiplW9ur/Rqlp05eUoUizATlGPnf3wpbAuXYzZHlCXZSop2Is/J2DDbE8Zz0GR9bqnsie758WAQ6b9u6Wm2EjB+pNej5CWhcvAVfFu2wnAfOF1eaFkFNZqbo='
    app: dogbook2022
    strategy: git
    on:
      branch:
        - 07-deployment
      repo: haraslub/dogbook
