---
sudo: required
dist: trusty
language: node_js
node_js:
  - 14.0.0

branches:
  only:
    - 07-deployment

cache:
  directories:
    - node_modules

services:
  - docker

env:
  global:
    - NODE_ENV=local # should be TEST!

install:
  - npm install

before_script:
  - sudo service postgresql stop
  - docker ps
  - npm run infra
  - sleep 5
  - npm run db:migrate:deploy # should be without :deploy (but test env does not work yet)

script:
  - npm run test:coverage

after_success:
  - echo Upload code coverage # homework

notifications:
  - email: false

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: $HEROKU_API_KEY
    app: dogbook2022
    strategy: git
    on:
      branch:
        - 07-deployment
      repo: haraslub/dogbook
